#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/usr/local/etc/X11/xinit/.Xresources

# merge in defaults and user settings

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$sysresources" ]; then
  xrdb -merge "$sysresources"
fi

